version: '3.8'

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"  # Внешний : внутренний 
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ollama_data:

  # docker-compose up
  # docker-compose exec ollama ollama pull nomic-embed-text
  # docker-compose exec ollama ollama pull codestral